name: Github Actions Demo
on: push
jobs:
  Example-Actions-Job:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

      # Use action located in http://github.com/actions
      - name: checkout repository code
        uses: actions/checkout@v2

      - run: echo "The ${{ github.repository }} repo has been cloned to the runner."

      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'

      - name: Display dotnet version
        run: dotnet --version
